# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-20 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='website',
            field=models.URLField(blank=True, max_length=120, null=True),
        ),
    ]
