# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-20 00:21
from __future__ import unicode_literals

from django.db import migrations


def move_site_data(apps, schema_editor):
    '''
    Move spotlight field data
    into new website field.
    '''
    Profile = apps.get_model('profiles', 'Profile')
    profiles = Profile.objects.all()

    for p in profiles:
        p.website = p.spotlight
        p.save()


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_website'),
    ]

    operations = [
        migrations.RunPython(move_site_data)
    ]
