# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='settings.STATIC_ROOT/anon.jpg', upload_to='photos/%Y/%m/%d'),
        ),
    ]
