# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-17 01:15
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20160503_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='get_full_name', unique=True),
        ),
    ]
