# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-20 00:53
from __future__ import unicode_literals

from django.db import migrations


def populate_spotlight_fields(apps, schema_editor):
    Profile = apps.get_model('profiles', 'Profile')
    Spotlight = apps.get_model('profiles', 'Spotlight')

    profiles = Profile.objects.all()

    for p in profiles:
        p.spotlight = Spotlight.objects.get_or_create(name='View my portfolio')[0]
        p.save()


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profile_spotlight'),
    ]

    operations = [
        migrations.RunPython(populate_spotlight_fields)
    ]
