# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-20 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20160619_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='website',
            field=models.URLField(max_length=120),
        ),
    ]
