# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-21 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20160619_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='occupations',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='profiles.Occupation'),
        ),
    ]
