# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-21 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20160620_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/%Y/%m/%d')),
                ('prefix', models.CharField(blank=True, max_length=50, null=True)),
                ('placeholder', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
