# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-21 03:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_socialmediaservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmediaservice',
            name='prefix',
        ),
    ]
