# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-21 03:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_remove_socialmediaservice_prefix'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(max_length=120)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_links', to='profiles.SocialMediaService')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='profiles.Profile')),
            ],
        ),
    ]
