# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-29 22:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_socialmedialink'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='socialmedialink',
            unique_together=set([('user_profile', 'service', 'link')]),
        ),
    ]
