# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-30 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_auto_20160629_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='social_links',
            field=models.ManyToManyField(blank=True, related_name='profiles', through='profiles.SocialMediaLink', to='profiles.SocialMediaService'),
        ),
    ]
