# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-30 00:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_profile_social_links'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='social_links',
            new_name='social',
        ),
    ]
